import React, { useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { Plus, X, Bot, Calendar, ArrowRight, ArrowLeft, Trash2, CheckSquare } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'

const initialTasks = [
  {
    id: 't-1',
    title: 'Implement WebSocket Auth & Handshake Middleware',
    description: 'Enforce HMAC token verification and client-side heartbeat pong response handling.',
    status: 'todo',
    priority: 'high',
    created_by: 'agent-planner',
    due_date: new Date(Date.now() + 172800000).toISOString()
  },
  {
    id: 't-2',
    title: 'Vector RAG Document Chunking Pipeline',
    description: 'Configure sliding window sentence splitter for PDF and Markdown files.',
    status: 'in_progress',
    priority: 'high',
    created_by: 'user',
    due_date: new Date(Date.now() + 259200000).toISOString()
  },
  {
    id: 't-3',
    title: 'Critic Validation Rule Engine Setup',
    description: 'Inspect generated agent markdown for source hallucination & citation validity.',
    status: 'in_progress',
    priority: 'medium',
    created_by: 'agent-planner',
    due_date: new Date(Date.now() + 432000000).toISOString()
  },
  {
    id: 't-4',
    title: 'Team Member Permission & Invite System',
    description: 'Workspace owner role checks and teammate email invitations.',
    status: 'done',
    priority: 'low',
    created_by: 'user',
    due_date: new Date(Date.now() - 86400000).toISOString()
  }
]

const Tasks = () => {
  const { id } = useParams()
  
  const [tasks, setTasks] = useState(initialTasks)
  const [showModal, setShowModal] = useState(false)
  
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [priority, setPriority] = useState('medium')
  const [dueDate, setDueDate] = useState('')
  const [creating, setCreating] = useState(false)

  const handleCreate = (e) => {
    e.preventDefault()
    if (!title.trim()) return

    setCreating(true)
    setTimeout(() => {
      const newTask = {
        id: `t-${Date.now()}`,
        title: title.trim(),
        description: description.trim(),
        status: 'todo',
        priority: priority,
        created_by: 'user',
        due_date: dueDate ? new Date(dueDate).toISOString() : null
      }
      
      setTasks(prev => [...prev, newTask])
      setShowModal(false)
      setTitle('')
      setDescription('')
      setPriority('medium')
      setDueDate('')
      setCreating(false)
    }, 300)
  }

  const moveTaskStatus = (taskId, newStatus) => {
    setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: newStatus } : t))
  }

  const handleDelete = (taskId) => {
    setTasks(prev => prev.filter(t => t.id !== taskId))
  }

  const handleDragStart = (e, taskId) => {
    e.dataTransfer.setData('text/plain', taskId)
  }

  const handleDrop = (e, status) => {
    e.preventDefault()
    const taskId = e.dataTransfer.getData('text/plain')
    if (taskId) {
      moveTaskStatus(taskId, status)
    }
  }

  const getPriorityBadge = (prio) => {
    switch (prio) {
      case 'high':
        return (
          <span className="text-[10px] font-semibold uppercase tracking-wider bg-[#FEF2F2] text-[#991B1B] border border-[#FEE2E2] px-2 py-0.5 rounded">
            High
          </span>
        )
      case 'medium':
        return (
          <span className="text-[10px] font-semibold uppercase tracking-wider bg-[#F4F4F2] text-[#18181B] border border-[#E4E4E0] px-2 py-0.5 rounded">
            Medium
          </span>
        )
      case 'low':
      default:
        return (
          <span className="text-[10px] font-semibold uppercase tracking-wider bg-[#F4F4F2] text-[#71717A] border border-[#E4E4E0] px-2 py-0.5 rounded">
            Low
          </span>
        )
    }
  }

  const columns = [
    { id: 'todo', name: 'To Do', dotColor: 'bg-[#71717A]' },
    { id: 'in_progress', name: 'In Progress', dotColor: 'bg-[#18181B]' },
    { id: 'done', name: 'Done', dotColor: 'bg-[#15803D]' }
  ]

  const getTasksForColumn = (colId) => {
    return tasks.filter(t => t.status === colId)
  }

  return (
    <div className="absolute inset-0 flex flex-col bg-[#F8F8F6] text-[#18181B] h-full p-4 sm:p-6 lg:p-8 overflow-y-auto select-none">
      {/* Header */}
      <div className="flex items-center justify-between mb-6 shrink-0">
        <div>
          <h2 className="font-display font-bold text-lg sm:text-xl text-[#18181B] tracking-tight">Milestone Kanban</h2>
          <p className="text-[#71717A] text-xs mt-0.5">Track deliverables generated by Planner Agent and team members.</p>
        </div>
        
        <button 
          onClick={() => setShowModal(true)}
          className="btn-primary flex items-center space-x-1.5 cursor-pointer text-xs sm:text-sm"
        >
          <Plus className="w-4 h-4" />
          <span>New Task</span>
        </button>
      </div>

      {/* Kanban Board */}
      {tasks.length === 0 ? (
        <div className="flex-1 flex flex-col items-center justify-center text-center p-8 bg-white border border-[#E4E4E0] rounded-2xl shadow-xs max-w-xl mx-auto my-auto">
          <div className="w-12 h-12 rounded-2xl bg-[#F4F4F2] flex items-center justify-center text-[#71717A] mb-4">
            <CheckSquare className="w-6 h-6" />
          </div>
          <h3 className="font-display font-bold text-base text-[#18181B]">No tasks on the board</h3>
          <p className="text-[#71717A] text-xs max-w-sm mt-1.5 mb-6 leading-relaxed">
            There are no active tasks. You can schedule deliverables manually or ask the Planner Agent in Copilot to generate a roadmap.
          </p>
          <div className="flex items-center space-x-3">
            <Link 
              to={`/w/${id}/copilot`} 
              className="btn-secondary flex items-center space-x-1.5"
            >
              <Bot className="w-4 h-4" />
              <span>Ask Copilot</span>
            </Link>
            <button 
              onClick={() => setShowModal(true)}
              className="btn-primary flex items-center space-x-1.5"
            >
              <Plus className="w-4 h-4" />
              <span>Create Task</span>
            </button>
          </div>
        </div>
      ) : (
        /* Kanban Columns Grid */
        <div className="flex-grow grid grid-cols-1 md:grid-cols-3 gap-5 min-h-[28rem] md:min-h-0 h-full overflow-y-auto md:overflow-hidden">
          {columns.map((col) => {
            const colTasks = getTasksForColumn(col.id)
            return (
              <div 
                key={col.id} 
                onDragOver={(e) => e.preventDefault()}
                onDrop={(e) => handleDrop(e, col.id)}
                className="bg-[#F4F4F2]/50 border border-[#E4E4E0] rounded-2xl flex flex-col h-full overflow-hidden min-h-[300px]"
              >
                {/* Column header */}
                <div className="p-3.5 px-4 bg-white border-b border-[#E4E4E0] flex items-center justify-between shrink-0">
                  <div className="flex items-center space-x-2">
                    <span className={`w-2 h-2 rounded-full ${col.dotColor}`}></span>
                    <h3 className="font-display font-bold text-xs text-[#18181B]">{col.name}</h3>
                  </div>
                  <span className="text-[11px] font-mono bg-[#F4F4F2] text-[#52525B] px-2 py-0.5 rounded-full font-semibold border border-[#E4E4E0]">
                    {colTasks.length}
                  </span>
                </div>

                {/* Column tasks cards */}
                <div className="flex-1 overflow-y-auto p-3 space-y-3">
                  {colTasks.map((task) => {
                    const isAgent = task.created_by?.startsWith('agent')
                    const dateFormatted = task.due_date ? new Date(task.due_date).toLocaleDateString([], { month: 'short', day: 'numeric' }) : null
                    
                    return (
                      <div
                        key={task.id}
                        draggable
                        onDragStart={(e) => handleDragStart(e, task.id)}
                        className="bg-white border border-[#E4E4E0] hover:border-[#18181B] hover:shadow-xs rounded-xl p-4 shadow-xs space-y-3 cursor-grab active:cursor-grabbing transition-all select-none group"
                      >
                        <div className="flex items-start justify-between">
                          <h4 className="text-xs sm:text-sm font-bold text-[#18181B] leading-snug break-words pr-2">
                            {task.title}
                          </h4>
                          <button 
                            onClick={() => handleDelete(task.id)}
                            className="text-[#A1A1AA] hover:text-[#DC2626] p-1 rounded hover:bg-[#FEF2F2] transition-colors shrink-0 cursor-pointer"
                            title="Delete Task"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>

                        {task.description && (
                          <p className="text-xs text-[#52525B] leading-relaxed break-words">{task.description}</p>
                        )}

                        <div className="flex items-center justify-between pt-2 border-t border-[#F4F4F2] text-[11px]">
                          {getPriorityBadge(task.priority)}

                          <div className="flex items-center space-x-2">
                            {isAgent ? (
                              <span className="flex items-center space-x-1 text-[#18181B] bg-[#F4F4F2] border border-[#E4E4E0] px-1.5 py-0.5 rounded text-[10px] font-semibold">
                                <Bot className="w-3 h-3" />
                                <span>Planner</span>
                              </span>
                            ) : null}

                            {dateFormatted ? (
                              <div className="flex items-center space-x-1 text-[#71717A] font-mono text-[10px]">
                                <Calendar className="w-3 h-3" />
                                <span>{dateFormatted}</span>
                              </div>
                            ) : null}
                          </div>
                        </div>

                        {/* Interactive Move buttons */}
                        <div className="flex items-center justify-between pt-1 border-t border-[#F4F4F2] text-[10px] text-[#71717A]">
                          <span>Move column:</span>
                          <div className="flex items-center space-x-1.5">
                            {col.id !== 'todo' && (
                              <button 
                                onClick={() => moveTaskStatus(task.id, col.id === 'done' ? 'in_progress' : 'todo')}
                                className="p-1 bg-[#F8F8F6] border border-[#E4E4E0] hover:bg-[#E7F0E9] hover:text-[#365742] rounded transition-colors cursor-pointer"
                                title="Move left"
                              >
                                <ArrowLeft className="w-3 h-3" />
                              </button>
                            )}
                            {col.id !== 'done' && (
                              <button 
                                onClick={() => moveTaskStatus(task.id, col.id === 'todo' ? 'in_progress' : 'done')}
                                className="p-1 bg-[#F8F8F6] border border-[#E4E4E0] hover:bg-[#E7F0E9] hover:text-[#365742] rounded transition-colors cursor-pointer"
                                title="Move right"
                              >
                                <ArrowRight className="w-3 h-3" />
                              </button>
                            )}
                          </div>
                        </div>
                      </div>
                    )
                  })}
                  {colTasks.length === 0 && (
                    <div className="border border-dashed border-[#E4E4E0] rounded-xl p-8 text-center select-none text-xs text-[#A1A1AA] font-sans">
                      No tasks in this stage
                    </div>
                  )}
                </div>
              </div>
            )
          })}
        </div>
      )}

      {/* Manual Task Modal */}
      <AnimatePresence>
        {showModal && (
          <div className="fixed inset-0 bg-[#18181B]/40 backdrop-blur-xs flex items-center justify-center p-4 z-50">
            <motion.div 
              initial={{ opacity: 0, scale: 0.97 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.97 }}
              transition={{ duration: 0.15 }}
              className="w-full max-w-md bg-white border border-[#E4E4E0] rounded-2xl p-6 shadow-2xl relative select-none"
            >
              <button 
                onClick={() => setShowModal(false)}
                className="absolute right-5 top-5 text-[#71717A] hover:text-[#18181B] p-1 rounded-lg hover:bg-[#F4F4F2] transition-colors cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>

              <h3 className="font-display font-bold text-lg text-[#18181B] tracking-tight mb-1">Create Task</h3>
              <p className="text-[#71717A] text-xs mb-5">Add a new deliverable to the workspace board.</p>

              <form onSubmit={handleCreate} className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-[#18181B]">Task Title</label>
                  <input 
                    type="text" 
                    required
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="e.g. Implement auth endpoints"
                    className="w-full bg-[#F8F8F6] border border-[#E4E4E0] text-[#18181B] text-sm px-3.5 py-2.5 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#18181B]/10 focus:border-[#18181B] transition-all placeholder:text-[#A1A1AA]"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-[#18181B]">Description (Optional)</label>
                  <textarea 
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="Provide context, acceptance criteria or details..."
                    rows="2"
                    className="w-full bg-[#F8F8F6] border border-[#E4E4E0] text-[#18181B] text-sm px-3.5 py-2.5 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#18181B]/10 focus:border-[#18181B] transition-all placeholder:text-[#A1A1AA] resize-none"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-[#18181B]">Priority</label>
                    <select 
                      value={priority}
                      onChange={(e) => setPriority(e.target.value)}
                      className="w-full bg-[#F8F8F6] border border-[#E4E4E0] text-[#18181B] text-sm px-3 py-2 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#18181B]/10 focus:border-[#18181B]"
                    >
                      <option value="low">Low</option>
                      <option value="medium">Medium</option>
                      <option value="high">High</option>
                    </select>
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-[#18181B]">Due Date</label>
                    <input 
                      type="date"
                      value={dueDate}
                      onChange={(e) => setDueDate(e.target.value)}
                      className="w-full bg-[#F8F8F6] border border-[#E4E4E0] text-[#18181B] text-sm px-3 py-2 rounded-xl focus:outline-none focus:ring-2 focus:ring-[#18181B]/10 focus:border-[#18181B]"
                    />
                  </div>
                </div>

                <div className="flex items-center justify-end space-x-3 pt-4 border-t border-[#F4F4F2]">
                  <button 
                    type="button"
                    onClick={() => setShowModal(false)}
                    className="btn-secondary"
                  >
                    Cancel
                  </button>
                  <button 
                    type="submit"
                    disabled={creating}
                    className="btn-primary"
                  >
                    {creating ? 'Creating...' : 'Create Task'}
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  )
}

export default Tasks
